export const MODULES = [
  {
    id: "earthquake",
    path: "/earthquake",
    icon: "🏗️",
    title: "Simulasi Gedung Tahan Gempa",
    shortTitle: "Gempa",
    description: "Lihat bagaimana gedung bertingkat bergoyang saat gempa bumi dan cara merancang gedung agar aman dari risiko runtuh.",
    category: "struktur",
  },
  {
    id: "steel-beam",
    path: "/steel-beam",
    icon: "🌉",
    title: "Kelenturan Jembatan & Balok",
    shortTitle: "Balok Baja",
    description: "Simulasikan seberapa melengkung jembatan atau balok baja ketika dilewati kendaraan atau beban berat.",
    category: "struktur",
  },
  {
    id: "wind-load",
    path: "/wind-load",
    icon: "💨",
    title: "Kekuatan Gedung Menahan Angin",
    shortTitle: "Beban Angin",
    description: "Hitung seberapa kuat dinding dan kaca gedung bertingkat dalam menahan tiupan angin kencang.",
    category: "struktur",
  },
  {
    id: "concrete",
    path: "/concrete",
    icon: "🧪",
    title: "Peracik Beton Ramah Lingkungan",
    shortTitle: "Beton Eco",
    description: "Racik beton yang kokoh namun rendah emisi karbon dengan memanfaatkan abu limbah batubara.",
    category: "material",
  },
  {
    id: "scheduling",
    path: "/scheduling",
    icon: "📅",
    title: "Penjadwalan Proyek Konstruksi",
    shortTitle: "Penjadwalan",
    description: "Belajar menyusun jadwal kerja pembangunan rumah agar selesai tepat waktu tanpa terlambat.",
    category: "material",
  },
  {
    id: "soil-bearing",
    path: "/soil-bearing",
    icon: "🪨",
    title: "Kekuatan Tanah Pondasi",
    shortTitle: "Tanah Pondasi",
    description: "Uji apakah tanah di bawah rumah Anda cukup kuat menahan berat bangunan agar tidak amblas.",
    category: "geoteknik",
  },
  {
    id: "retaining-wall",
    path: "/retaining-wall",
    icon: "🧱",
    title: "Dinding Penahan Tebing",
    shortTitle: "Dinding Tebing",
    description: "Simulasikan kekuatan dinding beton dalam menahan tekanan tanah tebing agar aman dari longsor.",
    category: "geoteknik",
  },
  {
    id: "hydrology",
    path: "/hydrology",
    icon: "🌊",
    title: "Bendungan Penangkal Banjir",
    shortTitle: "Bendungan",
    description: "Lihat bagaimana bendungan menampung air hujan deras agar kota di hilir bebas banjir.",
    category: "air",
  },
  {
    id: "pipe-flow",
    path: "/pipe-flow",
    icon: "🚰",
    title: "Tekanan Air Pipa Rumah",
    shortTitle: "Pipa Air",
    description: "Temukan alasan mengapa air keran bisa mengecil akibat panjang pipa dan banyaknya belokan.",
    category: "air",
  },
  {
    id: "traffic",
    path: "/traffic",
    icon: "🚦",
    title: "Kalkulator Kemacetan Jalan",
    shortTitle: "Macet Jalan",
    description: "Uji kapasitas jalan raya dan tentukan tingkat kenyamanan berkendara berdasarkan jumlah mobil.",
    category: "air",
  },
] as const

export type ModuleId = (typeof MODULES)[number]["id"]

export const CATEGORIES = [
  { id: "struktur", label: "🏢 Rekayasa Struktur", color: "civil" },
  { id: "material", label: "🧪 Material & Manajemen", color: "civil" },
  { id: "geoteknik", label: "🪨 Tanah & Pondasi", color: "earth" },
  { id: "air", label: "🌊 Air & Lalu Lintas", color: "civil" },
] as const
